### ISSUE TITLE
Bypass Auto

### ISSUE THREAD

**Issue by norsehealer** [BobNudd/Classic-AutoQuest#1]
I noticed some Guards will offer quest, however, with the addon you can't ask the guard for directions. Usually holding SHIFT is a way to stop the addon from the automation part.

Would be pretty great if we could setup a bypass key (control, shift, alt or other) to speak with NPCs after accepting their quest.

**Comment by ash-grennan** [comment]
That's a great idea, I'll get that implemented, thanks.

**Comment by rjacqu** [comment]
Yeah this is a huge issue, starting escorts, intitating dialogue with NPCs! really great work here otherwise

**Comment by ash-grennan** [comment]
@norsehealer @pbjtime This is now in the latest version available on Curseforge or Wowinterface, thanks both

**Comment by Jakobud** [comment]
I think this is a great feature. However the way it behaves currently, you have to continue holding the SHIFT button for every page of the quest/gossip frame. Like you gotta click the person with SHIFT, then if they have something to say you gotta continue holding SHIFT when clicking the quest title etc. It would be nice and seems to make sense that you only need to hold SHIFT when you initially click the NPC, then from that point on you don't need to continue holding SHIFT until you talk to them again or another quest NPC. Am I making sense?
